// Generated by Opic
import Foundation
import Metal

struct Type {
    // fields
}}

struct Voice {
    // fields
}}

struct Target {
    // fields
}}

struct Flow {
    // fields
}}

struct Reaction {
    // fields
}}

func compose(input: Any) -> Any {
    // {input -> output}
    return input
}

func emit(input: Any) -> Any {
    // {output -> target}
    return input
}

func reflect(input: Any) -> Any {
    // {flow -> type}
    return input
}

func handleerror(input: Any) -> Any {
    // {error -> str}
    return input
}

func escapetemplate(input: Any) -> Any {
    // {str -> str}
    return input
}

func escapejson(input: Any) -> Any {
    // {json -> str}
    return input
}

func escapejsonhtml(input: Any) -> Any {
    // {json -> html.safe}
    return input
}

func escapeformat(input: Any) -> Any {
    // {str -> str}
    return input
}

func fixtemplate(input: Any) -> Any {
    // {error.template -> str}
    return input
}

func composetemplate(input: Any) -> Any {
    // {template + data -> html}
    return input
}

func safeformat(input: Any) -> Any {
    // {template + data -> str}
    return input
}

func main(input: Any) -> Any {
    // {input -> default}
    return input
}

func main() {
    // {input -> default}
    print("opic: \(entry_point)")
}

main()